name: Updating data for stats

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Update data for SeleniumHQ/selenium
      run: |
        pipenv run status
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ORG: "seleniumhq"
        GITHUB_REPO: "selenium"
    - name: Update data for SeleniumHQ/docker-selenium
      run: |
        pipenv run status
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ORG: "seleniumhq"
        GITHUB_REPO: "docker-selenium"        
    - name: Update data for SeleniumHQ/selenium-ide
      run: |
        pipenv run status
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ORG: "seleniumhq"
        GITHUB_REPO: "selenium-ide"
    - name: Commit updated data
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main