name: Updating data for stats

on: 
  push:
  schedule:
    # Every day at 7:15 and 17:15 UTC:
    - cron:  '15 5,17 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Update data for SeleniumHQ/selenium
      run: |
        pipenv run get_stats
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ORG: "seleniumhq"
        GITHUB_REPO: "selenium"
    - name: Update data for SeleniumHQ/docker-selenium
      run: |
        pipenv run get_stats
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ORG: "seleniumhq"
        GITHUB_REPO: "docker-selenium"        
    - name: Update data for SeleniumHQ/selenium-ide
      run: |
        pipenv run get_stats
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ORG: "seleniumhq"
        GITHUB_REPO: "selenium-ide"
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Update data" -a
    - name: Commit updated data
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main